[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "kanban"
version = "0.5.0"
requires-python = ">=3.11"
dependencies = []
authors = [
    {name = "Philip Dow"}
]
description = "Kanban on the terminal"
readme = "README.md"
keywords = ["kanban", "task", "todo"]
license = "MIT"

[project.scripts]
kanban = "kanban.main:main"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = ["--import-mode=importlib"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
exclude = ["tests*"]
